### PR TITLE
Update xss-filters dep to latest 1.2.7

### PR DESCRIPTION
**Pull request by lorand-horvath**
I know it's old, but still...

### CODE REVIEW

**Comment by lorand-horvath** [comment]
@jsonmaur Not sure if you've noticed this PR, can you please merge this update?

**Comment by jsonmaur** [comment]
Thanks!

**Comment by jsonmaur** [comment]
Just realized I don't even have access to the NPM package anymore. I've put in a request to regain access and will cut a new version as soon as I hear back.

**Comment by lorand-horvath** [comment]
@jsonmaur Any news from NPM?

**Comment by jsonmaur** [comment]
@lorand-horvath No response to the ticket yet. I just sent another follow-up.

**Comment by jsonmaur** [comment]
@lorand-horvath Still haven't heard back from them. Apparently the current wait times are up to several months for these types of requests... sorry for the delay 😞

**Comment by jsonmaur** [comment]
@lorand-horvath Finally got the name back and published this in 0.1.2

**Pull request merged**
